### PR TITLE
State.hs :: findM -> fix typo in example

### PR DESCRIPTION
**Pull request by mitochon**
fix typo

### CODE REVIEW

**Comment by tonymorris** [comment]
Cheers big ears.

**Comment by louispan** [comment]
Is this correct? The implementation from the answers fork also fails this test case.
https://github.com/tonymorris/course/blob/804aaf5aecd93d3def632f32245b2c0eb88a68a8/src/Course/State.hs#L138

**Comment by louispan** [comment]
### Failure in src/Course/State.hs:132: expression `let p x = (\s -> (const $ pure (x == 'i')) =<< put (1+s)) =<< get in runState (findM p $ listh ['a'..'h']) 8'
expected: (Empty,8)
 but got: (Empty,16)

**Comment by mitochon** [comment]
You're right ... the original was correct (should be '0').
Let me submit a PR to revert back the change.

**Comment by mitochon** [comment]
Created PR #163

**Pull request merged**
